name: Check build

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: zulu
      - name: Build with Gradle
        run: ./gradlew assembleRelease
